# Generated by Django 2.2.11 on 2020-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default='null')),
                ('status', models.CharField(default='null', max_length=10)),
                ('last_name', models.CharField(default='null', max_length=40)),
                ('preferred_name', models.CharField(default='null', max_length=40)),
                ('manager_id', models.IntegerField(default='null')),
                ('work_phone', models.TextField(default='null')),
                ('personal_email', models.TextField(default='null')),
                ('location', models.TextField(default='null')),
                ('subordinates', models.TextField(default='null')),
                ('department', models.TextField(default='null')),
                ('employments', models.TextField(default='null')),
                ('gender', models.CharField(default='null', max_length=40)),
            ],
        ),
    ]
