# Generated by Django 2.2.11 on 2020-03-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0002_auto_20200313_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='gender',
        ),
        migrations.AlterField(
            model_name='detail',
            name='emp_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='manager_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='personal_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='preferred_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='work_phone',
            field=models.TextField(),
        ),
    ]
