# Generated by Django 2.2.11 on 2020-03-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0003_auto_20200313_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='manager_id',
        ),
    ]
