# Generated by Django 2.2.11 on 2020-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0004_remove_detail_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='emp_id',
            field=models.TextField(unique=True),
        ),
    ]
