# Generated by Django 2.2.11 on 2020-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0005_auto_20200313_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='employments_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='manager',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='subordinates_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='personal_email',
            field=models.CharField(max_length=50),
        ),
    ]
