# Generated by Django 2.2.11 on 2020-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0006_auto_20200314_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='employments_url',
        ),
        migrations.AddField(
            model_name='detail',
            name='Hire_date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='emp_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
