# Generated by Django 2.2.11 on 2020-03-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0007_auto_20200314_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Hire_date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='emp_type',
        ),
    ]
