# Generated by Django 2.2.11 on 2020-03-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0008_auto_20200314_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='manager',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
