# Generated by Django 2.2.11 on 2020-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0010_auto_20200314_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='manager_id',
            field=models.IntegerField(default='0'),
        ),
    ]
