# Generated by Django 2.2.11 on 2020-03-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0011_detail_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='manager',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='manager_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='personal_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='preferred_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='detail',
            name='subordinates_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='work_phone',
            field=models.TextField(),
        ),
    ]
