# Generated by Django 2.2.11 on 2020-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0015_detail_subordinates_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='subordinates_url',
        ),
        migrations.AddField(
            model_name='detail',
            name='department_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='location_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='manager_url',
            field=models.TextField(null=True),
        ),
    ]
