# Generated by Django 2.2.11 on 2020-03-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgchart', '0017_auto_20200316_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='personal_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='work_phone',
            field=models.TextField(null=True),
        ),
    ]
